[package]
name = "openvino-finder"
description = "A helper crate for finding OpenVINO installations on a system."
version = "0.3.0"
authors = ["Andrew Brown <andrew.brown@intel.com>"]
edition = "2018"

[dependencies]
